FROM ubuntu:23.10
ENV timezone=America/Sao_Paulo
RUN  ln -snf /usr/share/zoneinfo/${timezone} /etc/localtime && echo ${timezone} > /etc/timezone && \
 apt-get -y update && \
 apt-get install -y apache2 && \
 apt-get install -y php && \
 apt-get install -y php-xdebug && \
 #apt-get install -y php7.3-mysql && \
 apt-get install -y curl && \
 apt-get install -y inetutils-ping && \
 apt-get install -y nano
EXPOSE 80
WORKDIR /var/www/html
ENTRYPOINT /etc/init.d/apache2 start && /bin/bash
CMD ["true"]